Service tests - getUserId
Chicago-Artist-Guide/cag-backend-api pull request #15
Opened 2021-03-07 03:36 UTC by KaitlynSalemi

2021-03-07 15:17 UTC, prebollar15 commented on src/test/java/com/cag/cagbackendapi/services/user/UserServiceTest.kt
> +        val userId = "123e4567-e89b-12d3-a456-426614174000"
lines 84+85 can be replaced with 'val userId = UUID.randomUUID()'

2021-03-07 15:23 UTC, prebollar15 requested changes
Within userServiceTest.kt, could you add tests for a null/empty userid getting passed though and if the userDao returns a null value? That will cover the 3 exception scenarios that are present within the getUserById userService

2021-03-07 15:23 UTC, prebollar15 commented on src/test/java/com/cag/cagbackendapi/services/user/UserServiceTest.kt
> +        val userId = "123e4567-e89b-12d3-a456-426614174000"
Lines 84+85 can be replaced with `val userId = UUID.randomUUID()`

2021-03-07 15:41 UTC, CodyNicholson commented on src/test/java/com/cag/cagbackendapi/services/user/UserServiceTest.kt
> +    }
We need one more test for UserNotFound

2021-03-07 20:16 UTC, CodyNicholson approved these changes

2021-03-08 22:34 UTC, prebollar15 approved these changes

2021-03-08 22:44 UTC, merged